### ISSUE TITLE
What's the purpose of forbidding `out` and `in` as formal parameters?

### ISSUE THREAD

**Issue by oowekyala** [pmd/build-tools#14]
https://github.com/pmd/build-tools/blob/2ca92ff85f1bb44c9fa28448410f22c0a254891f/src/main/resources/net/sourceforge/pmd/pmd-dogfood-config.xml#L130

This has been ported from the deprecated rule [AvoidPrefixingMethodParameters](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#avoidprefixingmethodparameters).

It however seems kind of random to apply that to our codebase. The rule assumes that any parameter named `out` would be named so to communicate something about whether the parameter will be modified by the method. We never use such prefixes that way, so the rule's assumption is false from the start.  

On the other hand it's a widespread convention to name a parameter `out` when eg you're programming with a generic output stream. The whole point of using abstractions like OutputStream is to not care about where you're writing to, so I think it's part of the pattern to give a semantically empty name like `out`. The rule forbids it though.

**Comment by jsotuyod** [comment]
@oowekyala agreed, we can probably drop this config and use the default.
