### ISSUE TITLE
Failed Checkstyle import in IntelliJ

### ISSUE THREAD

**Issue by oowekyala** [pmd/build-tools#6]
When importing the checkstyle config in Checkstyle-IDEA plugin, I get an exception with the following message:

<pre>
org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be parsed.</b><br>cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of SuppressWithNearbyCommentFilter<br>The file has been blacklisted for 60s.</html>
</pre>

I can't find doc about that right now as sourceforge is offline

**Comment by jsotuyod** [comment]
In Checkstyle 8.1 `SuppressWithNearbyCommentFilter` was moved to be a child of `TreeWalker`. I believe your plugin is using an older version of Checkstyle, and therefore failing to load it.

Notice the latest Checkstyle version is 8.8

**Comment by oowekyala** [comment]
Thanks, I'll update my plugin and see if it's fixed

**Comment by oowekyala** [comment]
Ok the checkstyle version can be updated manually. I'll update the doc
